"""Add ecpay_trade_no to orders table

Revision ID: 6185b07ec593
Revises: 0b14d42f8cfc
Create Date: 2025-09-27 17:06:48.979124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6185b07ec593'
down_revision = '0b14d42f8cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecpay_trade_no', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('ecpay_trade_no')

    # ### end Alembic commands ###
